[tool.poetry]
name = "tutor-gpt"
version = "0.5.1"
description = "LangChain LLM application. Dynamic few-shot metaprompting for the task of tutoring."
authors = ["vintro <vince@plasticlabs.ai>", "VVoruganti <vineeth@plasticlabs.ai"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^1.0.0"
validators = "^0.20.0"
openai = "^1.3.8"
pexpect = "^4.8.0"
tiktoken = "^0.3.3"
supabase = "^1.0.4"
fastapi = "^0.101.1"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
requests = "^2.31.0"
sentry-sdk = {extras = ["fastapi"], version = "^1.31.0"}
langchain-mistralai = "^0.0.1"
langchain-community = "^0.0.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
